/**
 * scripts/seed.ts — Rimula demo/dev seed data
 *
 * Populates the net-new Rimula tables added in migrations 040-051:
 * Products, Vehicles, verified compatibility, Campaigns, Content +
 * translations + voice notes, Customer Requests, Trials, Engagement
 * events, Product interactions, WhatsApp sync log (Phase 1), plus
 * Markets, Regions, and the full §19 Member volumes on `contacts`,
 * and BA fields on the demo profile (Phase 2). Per §19 of
 * docs/RIMULA_BUILD_SPEC.md.
 *
 * §19 reference volumes (seeded exactly):
 *
 *   | Segment      | Total | WhatsApp confirmed |
 *   |--------------|-------|---------------------|
 *   | Mechanics    |   202 |                 154 |
 *   | Truck Owners |   255 |                 187 |
 *   | Drivers      |   387 |                 278 |
 *   | Total        |   844 |                 619 |
 *
 * across 20 markets grouped into 5 regions.
 *
 * WHY PROGRAMMATIC, NOT A .sql FILE: everything below goes through
 * `@supabase/supabase-js` — the same client every other admin/service
 * path in this codebase uses (mirrors `src/lib/automations/admin-client.ts`).
 * No raw SQL is written or executed here, so there's no dialect to get
 * wrong; every statement the server ever sees is a plain Postgres
 * INSERT/DELETE generated by the client library.
 *
 * LOCAL / DEV ONLY. Uses the Supabase Admin API
 * (`auth.admin.createUser`) to provision a demo login — this requires
 * `SUPABASE_SERVICE_ROLE_KEY` and bypasses RLS entirely, so never run
 * this against a hosted/production project. The demo account is
 * looked up by email and reused across runs, so a fresh
 * `accounts`/`profiles` row is only created once.
 *
 * Idempotent / re-runnable: every Rimula-domain row belonging to the
 * demo account is deleted and reinserted fresh on every run (see
 * CLEANUP_TABLES below). Row ids are regenerated each run — nothing
 * in the spec requires them to be stable across seed runs, only that
 * the script is safe to run repeatedly.
 *
 * Usage:
 *   npm run db:seed
 */

import { randomUUID } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

// ============================================================
// Setup
// ============================================================

loadEnvLocal();

const SUPABASE_URL = requireEnv('NEXT_PUBLIC_SUPABASE_URL');
const SERVICE_ROLE_KEY = requireEnv('SUPABASE_SERVICE_ROLE_KEY');

const DEMO_EMAIL = 'demo@rimula.local';
const DEMO_PASSWORD =
  process.env.RIMULA_SEED_DEMO_PASSWORD ?? 'rimula-demo-password';

const admin: SupabaseClient = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

type Row = Record<string, unknown>;

// Children first — every FK below is ON DELETE CASCADE/SET NULL, but
// deleting in dependency order keeps this readable and doesn't rely
// on cascade behaviour to avoid FK errors on tables that use SET NULL.
// `markets`/`regions` are listed after `contacts` (which references
// them) for the same reason, even though SET NULL means the order
// isn't load-bearing.
const CLEANUP_TABLES = [
  'product_interactions',
  'engagement_events',
  'whatsapp_sync_log',
  // Must precede `content`: a `broadcasts` row can have `content_id`
  // set with `template_name` null (a Content Studio scheduled post,
  // migration 053). `content_id` is `ON DELETE SET NULL`, but the
  // `broadcasts_send_source_check` CHECK constraint (added in the
  // same migration) requires template_name OR content_id — deleting
  // `content` while such a broadcast still references it trips that
  // CHECK via the SET NULL cascade. Deleting `broadcasts` first (its
  // own `account_id`, migration 017) avoids the conflict entirely.
  // `broadcast_recipients` isn't listed separately — it cascades from
  // `broadcasts` (`ON DELETE CASCADE`, migration 001).
  'broadcasts',
  'voice_notes',
  'content_translations',
  'content',
  'trials',
  'customer_requests',
  'deals',
  // `pipeline_stages` has no `account_id` column of its own (RLS
  // joins through `pipelines.account_id` — migration 017) so it can't
  // go through this generic per-table `.eq('account_id', ...)` loop;
  // it cascades away when `pipelines` below is deleted
  // (`pipeline_stages.pipeline_id ... ON DELETE CASCADE`, migration 001).
  'pipelines',
  'campaigns',
  'product_vehicles',
  'vehicles',
  'product_claims',
  'product_applications',
  'product_images',
  'products',
  'product_categories',
  'community_groups',
  'contacts',
  'markets',
  'regions',
];

// ============================================================
// Small helpers
// ============================================================

function loadEnvLocal(): void {
  const envPath = path.resolve(process.cwd(), '.env.local');
  if (!existsSync(envPath)) return;
  for (const line of readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (process.env[key] === undefined) process.env[key] = value;
  }
}

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(
      `Missing required env var ${name}. Set it in .env.local (see .env.local.example) before running the seed script.`
    );
  }
  return value;
}

function pick<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)];
}

function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function hoursAgo(n: number): string {
  return new Date(Date.now() - n * 3_600_000).toISOString();
}

function daysFromNow(n: number): string {
  return new Date(Date.now() + n * 86_400_000).toISOString().slice(0, 10);
}

// Supabase/PostgREST has no hard row-count limit on `.insert()`, but
// chunking keeps payload size and statement time bounded regardless
// of how large a seed section grows (the 844-row Member insert is
// the reason this exists).
const INSERT_CHUNK_SIZE = 250;

async function insert(table: string, rows: Row[]): Promise<void> {
  if (rows.length === 0) return;
  for (let i = 0; i < rows.length; i += INSERT_CHUNK_SIZE) {
    const chunk = rows.slice(i, i + INSERT_CHUNK_SIZE);
    const { error } = await admin.from(table).insert(chunk);
    if (error) {
      throw new Error(
        `Failed to insert into "${table}" (rows ${i}-${i + chunk.length - 1}): ${error.message}`
      );
    }
  }
}

async function cleanup(accountId: string): Promise<void> {
  for (const table of CLEANUP_TABLES) {
    const { error } = await admin
      .from(table)
      .delete()
      .eq('account_id', accountId);
    if (error) {
      throw new Error(`Failed to clean up "${table}": ${error.message}`);
    }
  }
}

// ============================================================
// Demo account bootstrap
// ============================================================

async function findUserByEmail(email: string) {
  let page = 1;
  const perPage = 200;
  for (;;) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage });
    if (error) throw new Error(`listUsers failed: ${error.message}`);
    const match = data.users.find((u) => u.email === email);
    if (match) return match;
    if (data.users.length < perPage) return null;
    page += 1;
  }
}

async function getOrCreateDemoUser(): Promise<string> {
  const { data, error } = await admin.auth.admin.createUser({
    email: DEMO_EMAIL,
    password: DEMO_PASSWORD,
    email_confirm: true,
    user_metadata: { full_name: 'Rimula Demo Admin' },
  });
  if (!error && data.user) {
    console.log(`Created demo user ${DEMO_EMAIL} (${data.user.id})`);
    return data.user.id;
  }

  // Most likely cause of failure on a re-run: the user already
  // exists. Look it up instead of treating that as fatal.
  const existing = await findUserByEmail(DEMO_EMAIL);
  if (existing) {
    console.log(`Reusing existing demo user ${DEMO_EMAIL} (${existing.id})`);
    return existing.id;
  }

  throw new Error(
    `Could not create or find demo user ${DEMO_EMAIL}: ${error?.message ?? 'unknown error'}`
  );
}

async function getAccountId(userId: string): Promise<string> {
  const { data, error } = await admin
    .from('profiles')
    .select('account_id')
    .eq('user_id', userId)
    .single();
  if (error || !data) {
    throw new Error(
      `No profile/account found for demo user ${userId}. Was migration 017 (handle_new_user trigger) applied? (${error?.message ?? 'no rows'})`
    );
  }
  return data.account_id as string;
}

// ============================================================
// Seed sections — Phase 1 (Products/Vehicles/Campaigns/Content/...)
// ============================================================

async function seedCommunityGroup(
  accountId: string,
  userId: string
): Promise<void> {
  await insert('community_groups', [
    {
      account_id: accountId,
      name: 'Rimula Announcements',
      description:
        'Brand-to-audience broadcast destination for community members (Mechanics, Truck Drivers, Truck Owners, BAs, Other).',
      status: 'active',
      created_by: userId,
    },
  ]);
}

async function seedProductCategories(
  accountId: string
): Promise<Map<string, string>> {
  const categories = [
    {
      name: 'Heavy Duty Diesel Engine Oils',
      description:
        'Engine oils for trucks, buses, and heavy commercial fleets.',
    },
    {
      name: 'Passenger Car Motor Oils',
      description: 'Engine oils for cars and light passenger vehicles.',
    },
    {
      name: 'Transmission & Gear Oils',
      description: 'Automatic transmission fluids and manual gear oils.',
    },
    { name: 'Greases', description: 'Multi-purpose and specialty greases.' },
    {
      name: 'Coolants',
      description: 'Engine coolants and antifreeze concentrates.',
    },
  ].map((c) => ({ id: randomUUID(), ...c }));

  await insert(
    'product_categories',
    categories.map((c) => ({ ...c, account_id: accountId }))
  );
  return new Map(categories.map((c) => [c.name, c.id]));
}

interface ProductSeed {
  code: string;
  category: string;
  name: string;
  description: string;
  shortDescription: string;
  longDescription: string;
  keyFeatures: string[];
  benefits: string[];
  vehicleTypes: string[];
  recommendedVehicles: string[];
  engineTypes: string[];
  packaging: string;
  status: 'draft' | 'pending_review' | 'published' | 'archived';
}

const PRODUCT_SEEDS: ProductSeed[] = [
  {
    code: 'RIM-HDD-15W40',
    category: 'Heavy Duty Diesel Engine Oils',
    name: 'Heavy Duty Diesel Engine Oil 15W-40',
    description:
      'General-purpose heavy duty diesel engine oil for mixed-fleet operation.',
    shortDescription:
      'Reliable protection for heavy-duty diesel engines under demanding conditions.',
    longDescription:
      'Formulated for extended drain intervals in heavy-duty diesel engines. Confirm current OEM approvals against the manufacturer datasheet before quoting a customer — see product_claims for administrator-approved statements.',
    keyFeatures: [
      'High-temperature oxidation stability',
      'Soot handling for extended oil life',
      'Compatible with common heavy-duty diesel engine families',
    ],
    benefits: [
      'Helps protect against wear in demanding fleet duty cycles',
      'Supports extended drain intervals where approved',
    ],
    vehicleTypes: ['Heavy Truck', 'Bus'],
    recommendedVehicles: ['Fleet Manufacturer A H1', 'Fleet Manufacturer B H2'],
    engineTypes: ['Diesel I6 Turbo', 'Diesel V8 Turbo'],
    packaging: '20L pail / 209L drum',
    status: 'published',
  },
  {
    code: 'RIM-HDD-10W30',
    category: 'Heavy Duty Diesel Engine Oils',
    name: 'Heavy Duty Diesel Engine Oil 10W-30',
    description:
      'Lower-viscosity heavy duty diesel oil for fuel-economy-focused fleets.',
    shortDescription:
      'Fuel-economy oriented protection for modern diesel engines.',
    longDescription:
      'A lower-viscosity option for fleets prioritising fuel economy. Confirm current OEM approvals against the manufacturer datasheet before quoting a customer.',
    keyFeatures: [
      'Lower viscosity for fuel-economy benefit potential',
      'Robust wear protection',
    ],
    benefits: [
      'May support improved fuel economy versus a heavier-grade oil, subject to OEM approval',
    ],
    vehicleTypes: ['Heavy Truck', 'Light Commercial Vehicle'],
    recommendedVehicles: ['Fleet Manufacturer A H1', 'Fleet Manufacturer C L1'],
    engineTypes: ['Diesel I6 Turbo', 'Diesel I4 Turbo'],
    packaging: '20L pail / 209L drum',
    status: 'published',
  },
  {
    code: 'RIM-HDD-5W30-SYN',
    category: 'Heavy Duty Diesel Engine Oils',
    name: 'Synthetic Heavy Duty Diesel Engine Oil 5W-30',
    description:
      'Full-synthetic heavy duty diesel oil for the latest low-emission engines.',
    shortDescription:
      'Full-synthetic protection for modern low-emission diesel platforms.',
    longDescription:
      'A full-synthetic formulation targeted at newer low-emission diesel engine designs. Confirm current OEM approvals against the manufacturer datasheet before quoting a customer.',
    keyFeatures: [
      'Full-synthetic base stock',
      'Designed for low-emission aftertreatment compatibility',
    ],
    benefits: [
      'Aims to support engine cleanliness and aftertreatment system compatibility',
    ],
    vehicleTypes: ['Heavy Truck'],
    recommendedVehicles: ['Fleet Manufacturer B H2'],
    engineTypes: ['Diesel V8 Turbo'],
    packaging: '20L pail',
    status: 'published',
  },
  {
    code: 'RIM-PCM-5W30',
    category: 'Passenger Car Motor Oils',
    name: 'Passenger Car Motor Oil 5W-30',
    description: 'General-purpose passenger car engine oil.',
    shortDescription: 'Everyday protection for petrol passenger cars.',
    longDescription:
      'Suitable for a broad range of petrol passenger car engines. Confirm current OEM approvals against the manufacturer datasheet before quoting a customer.',
    keyFeatures: [
      'Broad OEM compatibility potential',
      'Good cold-start flow characteristics',
    ],
    benefits: ['Supports everyday reliability for daily-driver use'],
    vehicleTypes: ['Passenger Car'],
    recommendedVehicles: ['Auto Manufacturer D C1', 'Auto Manufacturer D C2'],
    engineTypes: ['Petrol I4', 'Petrol I4 Turbo'],
    packaging: '1L / 4L bottle',
    status: 'published',
  },
  {
    code: 'RIM-PCM-10W40',
    category: 'Passenger Car Motor Oils',
    name: 'Passenger Car Motor Oil 10W-40',
    description:
      'Higher-viscosity passenger car oil for older engines / hot climates.',
    shortDescription:
      'A heavier-grade option for older engines or high-ambient-temperature markets.',
    longDescription:
      'Aimed at older engine designs or markets with sustained high ambient temperatures. Confirm current OEM approvals against the manufacturer datasheet before quoting a customer.',
    keyFeatures: ['Heavier viscosity grade for worn-engine tolerance'],
    benefits: ['May help reduce oil consumption in higher-mileage engines'],
    vehicleTypes: ['Passenger Car'],
    recommendedVehicles: ['Auto Manufacturer D C1'],
    engineTypes: ['Petrol I4'],
    packaging: '1L / 4L bottle',
    status: 'pending_review',
  },
  {
    code: 'RIM-ATF-III',
    category: 'Transmission & Gear Oils',
    name: 'Automatic Transmission Fluid III',
    description: 'General-purpose automatic transmission fluid.',
    shortDescription: 'Smooth shifting protection for automatic transmissions.',
    longDescription:
      'A general-purpose ATF. Confirm current OEM approvals against the manufacturer datasheet before quoting a customer.',
    keyFeatures: [
      'Friction durability for smooth shifting',
      'Oxidation resistance',
    ],
    benefits: ['Supports consistent shift feel over the service interval'],
    vehicleTypes: ['Passenger Car'],
    recommendedVehicles: ['Auto Manufacturer D C1', 'Auto Manufacturer D C2'],
    engineTypes: ['Petrol I4', 'Petrol I4 Turbo'],
    packaging: '1L / 4L bottle',
    status: 'published',
  },
  {
    code: 'RIM-GEAR-85W140',
    category: 'Transmission & Gear Oils',
    name: 'Heavy Duty Gear Oil 85W-140',
    description: 'Heavy duty manual gear/axle oil.',
    shortDescription:
      'Robust protection for heavy-duty axles and manual gearboxes.',
    longDescription:
      'Formulated for heavy-duty axle and manual gearbox applications. Confirm current OEM approvals against the manufacturer datasheet before quoting a customer.',
    keyFeatures: [
      'Extreme-pressure additive package',
      'Thermal stability under sustained load',
    ],
    benefits: ['Supports gear and bearing protection in heavy-duty axles'],
    vehicleTypes: ['Heavy Truck'],
    recommendedVehicles: ['Fleet Manufacturer A H1', 'Fleet Manufacturer B H2'],
    engineTypes: ['Diesel I6 Turbo', 'Diesel V8 Turbo'],
    packaging: '20L pail / 209L drum',
    status: 'published',
  },
  {
    code: 'RIM-GREASE-EP2',
    category: 'Greases',
    name: 'Multi-Purpose EP2 Grease',
    description: 'General-purpose extreme-pressure grease.',
    shortDescription:
      'General-purpose lubrication for chassis and wheel-bearing points.',
    longDescription:
      'A multi-purpose EP2 grease suitable for common chassis lubrication points. Confirm current OEM approvals against the manufacturer datasheet before quoting a customer.',
    keyFeatures: ['Extreme-pressure additive package', 'Water-resistance'],
    benefits: ['Supports general chassis and bearing lubrication needs'],
    vehicleTypes: ['Heavy Truck', 'Bus', 'Passenger Car'],
    recommendedVehicles: [],
    engineTypes: [],
    packaging: '400g cartridge / 18kg pail',
    status: 'draft',
  },
  {
    code: 'RIM-COOL-OAT',
    category: 'Coolants',
    name: 'Extended Life OAT Coolant Concentrate',
    description: 'Organic Acid Technology coolant concentrate.',
    shortDescription: 'Extended-life coolant for mixed engine fleets.',
    longDescription:
      'An OAT-technology coolant concentrate intended for dilution per the datasheet. Confirm current OEM approvals against the manufacturer datasheet before quoting a customer.',
    keyFeatures: [
      'Extended service life versus conventional coolant',
      'Broad metal compatibility',
    ],
    benefits: ['Supports longer intervals between coolant service'],
    vehicleTypes: ['Heavy Truck', 'Bus', 'Passenger Car'],
    recommendedVehicles: [],
    engineTypes: [],
    packaging: '5L / 20L container',
    status: 'published',
  },
  {
    code: 'RIM-HDD-20W50',
    category: 'Heavy Duty Diesel Engine Oils',
    name: 'Heavy Duty Diesel Engine Oil 20W-50',
    description:
      'Higher-viscosity heavy duty diesel oil for older / high-mileage engines.',
    shortDescription:
      'A heavier-grade option for older heavy-duty diesel engines.',
    longDescription:
      'Retained for legacy fleet support; superseded by newer grades for most new equipment. Confirm current OEM approvals against the manufacturer datasheet before quoting a customer.',
    keyFeatures: ['Heavier viscosity for worn-engine tolerance'],
    benefits: [
      'May help reduce oil consumption in higher-mileage diesel engines',
    ],
    vehicleTypes: ['Generator'],
    recommendedVehicles: ['Power Equipment Mfr E G1'],
    engineTypes: ['Diesel I4'],
    packaging: '20L pail / 209L drum',
    status: 'archived',
  },
];

async function seedProducts(
  accountId: string,
  userId: string,
  categoryIds: Map<string, string>
): Promise<Map<string, string>> {
  const productIds = new Map(PRODUCT_SEEDS.map((p) => [p.code, randomUUID()]));

  await insert(
    'products',
    PRODUCT_SEEDS.map((p) => ({
      id: productIds.get(p.code),
      account_id: accountId,
      category_id: categoryIds.get(p.category) ?? null,
      product_code: p.code,
      product_name: p.name,
      description: p.description,
      short_description: p.shortDescription,
      long_description: p.longDescription,
      key_features: p.keyFeatures,
      benefits: p.benefits,
      vehicle_types: p.vehicleTypes,
      recommended_vehicles: p.recommendedVehicles,
      engine_types: p.engineTypes,
      packaging: p.packaging,
      status: p.status,
      created_by: userId,
    }))
  );
  return productIds;
}

async function seedProductMedia(
  accountId: string,
  productIds: Map<string, string>
): Promise<void> {
  const images = [
    {
      code: 'RIM-HDD-15W40',
      filename: 'rim-hdd-15w40-front.jpg',
      alt: 'front label',
      position: 0,
    },
    {
      code: 'RIM-HDD-15W40',
      filename: 'rim-hdd-15w40-back.jpg',
      alt: 'back label',
      position: 1,
    },
    {
      code: 'RIM-PCM-5W30',
      filename: 'rim-pcm-5w30-front.jpg',
      alt: 'front label',
      position: 0,
    },
    {
      code: 'RIM-COOL-OAT',
      filename: 'rim-coolant-oat-front.jpg',
      alt: 'front label',
      position: 0,
    },
  ];
  await insert(
    'product_images',
    images.map((img) => ({
      account_id: accountId,
      product_id: productIds.get(img.code),
      storage_path: `account-${accountId}/products/${img.filename}`,
      alt_text: `Rimula ${img.code} — ${img.alt}`,
      position: img.position,
    }))
  );

  const applications = [
    {
      code: 'RIM-HDD-15W40',
      application: 'Long-haul heavy truck fleets',
      notes: 'Most-requested application for this grade among heavy-truck BAs.',
    },
    {
      code: 'RIM-HDD-15W40',
      application: 'Intercity bus operators',
      notes: null,
    },
    {
      code: 'RIM-ATF-III',
      application: 'Passenger car automatic transmissions',
      notes:
        'Confirm fluid type against the vehicle handbook before recommending.',
    },
    {
      code: 'RIM-COOL-OAT',
      application: 'Mixed diesel/petrol fleet coolant standardisation',
      notes: null,
    },
  ];
  await insert(
    'product_applications',
    applications.map((a) => ({
      account_id: accountId,
      product_id: productIds.get(a.code),
      application: a.application,
      notes: a.notes,
    }))
  );
}

async function seedProductClaims(
  accountId: string,
  userId: string,
  productIds: Map<string, string>
): Promise<void> {
  const claims: {
    code: string;
    text: string;
    status: 'draft' | 'pending_review' | 'approved' | 'rejected';
  }[] = [
    {
      code: 'RIM-HDD-15W40',
      text: 'Formulated for extended drain intervals in heavy-duty diesel engines (see datasheet for approved interval by OEM).',
      status: 'approved',
    },
    {
      code: 'RIM-HDD-15W40',
      text: 'Suitable for all heavy-duty diesel engines regardless of OEM approval.',
      status: 'rejected',
    },
    {
      code: 'RIM-PCM-5W30',
      text: 'Meets common OEM specifications for petrol passenger cars (verify against current datasheet per vehicle).',
      status: 'approved',
    },
    {
      code: 'RIM-COOL-OAT',
      text: 'Extended-life formulation intended to reduce coolant service frequency versus a conventional coolant.',
      status: 'pending_review',
    },
    {
      code: 'RIM-PCM-10W40',
      text: 'Improves fuel economy by 10% in all vehicles.',
      status: 'draft',
    },
  ];

  await insert(
    'product_claims',
    claims.map((c) => ({
      account_id: accountId,
      product_id: productIds.get(c.code),
      claim_text: c.text,
      status: c.status,
      created_by: userId,
      approved_by: c.status === 'approved' ? userId : null,
      approved_at: c.status === 'approved' ? hoursAgo(72) : null,
    }))
  );
}

interface VehicleSeed {
  key: string;
  vehicleType: string;
  manufacturer: string;
  model: string;
  engine: string;
}

const VEHICLE_SEEDS: VehicleSeed[] = [
  {
    key: 'H1',
    vehicleType: 'Heavy Truck',
    manufacturer: 'Fleet Manufacturer A',
    model: 'H1',
    engine: 'Diesel I6 Turbo',
  },
  {
    key: 'H2',
    vehicleType: 'Heavy Truck',
    manufacturer: 'Fleet Manufacturer B',
    model: 'H2',
    engine: 'Diesel V8 Turbo',
  },
  {
    key: 'B1',
    vehicleType: 'Bus',
    manufacturer: 'Fleet Manufacturer A',
    model: 'B1',
    engine: 'Diesel I6',
  },
  {
    key: 'L1',
    vehicleType: 'Light Commercial Vehicle',
    manufacturer: 'Fleet Manufacturer C',
    model: 'L1',
    engine: 'Diesel I4 Turbo',
  },
  {
    key: 'P1',
    vehicleType: 'Pickup',
    manufacturer: 'Fleet Manufacturer C',
    model: 'P1',
    engine: 'Diesel I4',
  },
  {
    key: 'C1',
    vehicleType: 'Passenger Car',
    manufacturer: 'Auto Manufacturer D',
    model: 'C1',
    engine: 'Petrol I4',
  },
  {
    key: 'C2',
    vehicleType: 'Passenger Car',
    manufacturer: 'Auto Manufacturer D',
    model: 'C2',
    engine: 'Petrol I4 Turbo',
  },
  {
    key: 'G1',
    vehicleType: 'Generator',
    manufacturer: 'Power Equipment Mfr E',
    model: 'G1',
    engine: 'Diesel I4',
  },
];

async function seedVehicles(accountId: string): Promise<Map<string, string>> {
  const vehicleIds = new Map(VEHICLE_SEEDS.map((v) => [v.key, randomUUID()]));
  await insert(
    'vehicles',
    VEHICLE_SEEDS.map((v) => ({
      id: vehicleIds.get(v.key),
      account_id: accountId,
      vehicle_type: v.vehicleType,
      manufacturer: v.manufacturer,
      model: v.model,
      engine: v.engine,
    }))
  );
  return vehicleIds;
}

async function seedProductVehicles(
  accountId: string,
  userId: string,
  productIds: Map<string, string>,
  vehicleIds: Map<string, string>
): Promise<void> {
  const compatibility: { code: string; key: string; notes?: string }[] = [
    { code: 'RIM-HDD-15W40', key: 'H1' },
    { code: 'RIM-HDD-15W40', key: 'H2' },
    { code: 'RIM-HDD-15W40', key: 'B1' },
    { code: 'RIM-HDD-10W30', key: 'H1' },
    { code: 'RIM-HDD-10W30', key: 'L1' },
    {
      code: 'RIM-HDD-5W30-SYN',
      key: 'H2',
      notes:
        "Confirmed against manufacturer B's latest low-emission diesel spec.",
    },
    { code: 'RIM-PCM-5W30', key: 'C1' },
    { code: 'RIM-PCM-5W30', key: 'C2' },
    { code: 'RIM-PCM-10W40', key: 'C1' },
    { code: 'RIM-ATF-III', key: 'C1' },
    { code: 'RIM-ATF-III', key: 'C2' },
    { code: 'RIM-GEAR-85W140', key: 'H1' },
    { code: 'RIM-GEAR-85W140', key: 'H2' },
    { code: 'RIM-COOL-OAT', key: 'H1' },
    { code: 'RIM-COOL-OAT', key: 'H2' },
    { code: 'RIM-COOL-OAT', key: 'C1' },
    { code: 'RIM-HDD-20W50', key: 'G1' },
  ];

  await insert(
    'product_vehicles',
    compatibility.map((c) => ({
      account_id: accountId,
      product_id: productIds.get(c.code),
      vehicle_id: vehicleIds.get(c.key),
      verified_by: userId,
      notes: c.notes ?? null,
    }))
  );
}

interface CampaignSeed {
  key: string;
  name: string;
  productCode: string | null;
  startDate: string | null;
  endDate: string | null;
  objective: string;
  audience: Row;
  status: 'draft' | 'active' | 'paused' | 'completed' | 'archived';
  cost: number | null;
}

const CAMPAIGN_SEEDS: CampaignSeed[] = [
  {
    key: 'fleet-checkup',
    name: 'Fleet Check-Up Season',
    productCode: 'RIM-HDD-15W40',
    startDate: daysFromNow(-10),
    endDate: daysFromNow(20),
    objective:
      'Drive trial requests for Heavy Duty Diesel Engine Oil 15W-40 among heavy-truck drivers and mechanics.',
    audience: {
      roles: ['Mechanic', 'Truck Driver', 'Truck Owner'],
      markets: ['all'],
    },
    status: 'active',
    cost: 150000,
  },
  {
    key: 'passenger-car-push',
    name: 'Passenger Car Oil Change Push',
    productCode: 'RIM-PCM-5W30',
    startDate: daysFromNow(-60),
    endDate: daysFromNow(-15),
    objective: 'Seasonal reminder campaign for passenger car oil changes.',
    audience: { roles: ['Other'], markets: ['all'] },
    status: 'completed',
    cost: 60000,
  },
  {
    key: 'winter-coolant',
    name: 'Winter Coolant Readiness',
    productCode: 'RIM-COOL-OAT',
    startDate: null,
    endDate: null,
    objective: 'Educate the community on coolant service ahead of winter.',
    audience: { roles: ['Mechanic', 'Truck Owner'], markets: ['all'] },
    status: 'draft',
    cost: null,
  },
];

async function seedCampaigns(
  accountId: string,
  userId: string,
  productIds: Map<string, string>
): Promise<Map<string, string>> {
  const campaignIds = new Map(CAMPAIGN_SEEDS.map((c) => [c.key, randomUUID()]));
  await insert(
    'campaigns',
    CAMPAIGN_SEEDS.map((c) => ({
      id: campaignIds.get(c.key),
      account_id: accountId,
      campaign_name: c.name,
      product_id: c.productCode ? productIds.get(c.productCode) : null,
      start_date: c.startDate,
      end_date: c.endDate,
      objective: c.objective,
      audience: c.audience,
      status: c.status,
      cost: c.cost,
      created_by: userId,
    }))
  );
  return campaignIds;
}

// ============================================================
// Seed sections — Phase 2 (Markets/Regions, Members, BA fields)
// ============================================================

interface RegionSeed {
  key: string;
  name: string;
}

const REGIONS_SEEDS: RegionSeed[] = [
  { key: 'punjab', name: 'Punjab' },
  { key: 'sindh', name: 'Sindh' },
  { key: 'kpk', name: 'Khyber Pakhtunkhwa' },
  { key: 'balochistan', name: 'Balochistan' },
  { key: 'ict', name: 'Islamabad Capital Territory' },
];

interface MarketSeed {
  key: string;
  name: string;
  region: string;
}

// Exactly 20 markets (§19), grouped under the 5 regions above.
const MARKETS_SEEDS: MarketSeed[] = [
  { key: 'lahore', name: 'Lahore', region: 'punjab' },
  { key: 'rawalpindi', name: 'Rawalpindi', region: 'punjab' },
  { key: 'faisalabad', name: 'Faisalabad', region: 'punjab' },
  { key: 'multan', name: 'Multan', region: 'punjab' },
  { key: 'sialkot', name: 'Sialkot', region: 'punjab' },
  { key: 'gujranwala', name: 'Gujranwala', region: 'punjab' },
  { key: 'bahawalpur', name: 'Bahawalpur', region: 'punjab' },
  { key: 'sargodha', name: 'Sargodha', region: 'punjab' },
  { key: 'gujrat', name: 'Gujrat', region: 'punjab' },
  { key: 'karachi', name: 'Karachi', region: 'sindh' },
  { key: 'hyderabad', name: 'Hyderabad', region: 'sindh' },
  { key: 'sukkur', name: 'Sukkur', region: 'sindh' },
  { key: 'larkana', name: 'Larkana', region: 'sindh' },
  { key: 'mirpurkhas', name: 'Mirpurkhas', region: 'sindh' },
  { key: 'peshawar', name: 'Peshawar', region: 'kpk' },
  { key: 'mardan', name: 'Mardan', region: 'kpk' },
  { key: 'abbottabad', name: 'Abbottabad', region: 'kpk' },
  { key: 'quetta', name: 'Quetta', region: 'balochistan' },
  { key: 'gwadar', name: 'Gwadar', region: 'balochistan' },
  { key: 'islamabad', name: 'Islamabad', region: 'ict' },
];

async function seedMarketsRegions(
  accountId: string
): Promise<{ regionIds: Map<string, string>; marketIds: Map<string, string> }> {
  const regionIds = new Map(REGIONS_SEEDS.map((r) => [r.key, randomUUID()]));
  await insert(
    'regions',
    REGIONS_SEEDS.map((r) => ({
      id: regionIds.get(r.key),
      account_id: accountId,
      name: r.name,
    }))
  );

  const marketIds = new Map(MARKETS_SEEDS.map((m) => [m.key, randomUUID()]));
  await insert(
    'markets',
    MARKETS_SEEDS.map((m) => ({
      id: marketIds.get(m.key),
      account_id: accountId,
      region_id: regionIds.get(m.region),
      name: m.name,
    }))
  );

  return { regionIds, marketIds };
}

// Gives the single demo login usable BA fields (region/market/status/
// capacity/languages) so it's a coherent BA target for
// `assigned_ba_id` / `translated_by` / `verified_by` elsewhere in this
// script, not just an account owner with everything null. Uses
// `.update()` with the service-role client, which bypasses RLS —
// `profiles_update` (migration 017) only allows a row's own user to
// update it via the normal client, so an admin-editing-a-teammate UI
// will need a server-side endpoint later; not needed here since the
// demo user is updating (effectively) itself.
async function seedDemoUserBaFields(
  userId: string,
  regionIds: Map<string, string>,
  marketIds: Map<string, string>
): Promise<void> {
  const { error } = await admin
    .from('profiles')
    .update({
      region_id: regionIds.get('punjab'),
      market_id: marketIds.get('lahore'),
      ba_status: 'active',
      open_leads: 0,
      capacity: 25,
      languages: ['ur', 'ps', 'pa'],
    })
    .eq('user_id', userId);
  if (error) {
    throw new Error(`Failed to set demo BA profile fields: ${error.message}`);
  }
}

interface NamedMemberSeed {
  key: string;
  name: string;
  company: string | null;
  role: 'Mechanic' | 'Truck Owner' | 'Truck Driver';
}

// The same 20 people the Phase 1 seed used as demo contacts, now with
// a role assigned (derived from their company, where they had one —
// e.g. "City Auto Workshop" -> Mechanic, "Farooq Transport Co." ->
// Truck Owner). Kept as named individuals — rather than folding them
// into the anonymous bulk-generated pool below — because
// `customer_requests`/`trials` reference them by name in their
// narrative `notes` fields; `namedContactIds` (returned by
// `seedDemoContacts`) is how those sections look them up.
const NAMED_MEMBER_SEEDS: NamedMemberSeed[] = [
  {
    key: 'ahmed-raza',
    name: 'Ahmed Raza',
    company: 'Independent Mechanic',
    role: 'Mechanic',
  },
  {
    key: 'bilal-hussain',
    name: 'Bilal Hussain',
    company: 'City Auto Workshop',
    role: 'Mechanic',
  },
  {
    key: 'chaudhry-farooq',
    name: 'Chaudhry Farooq',
    company: 'Farooq Transport Co.',
    role: 'Truck Owner',
  },
  {
    key: 'danish-iqbal',
    name: 'Danish Iqbal',
    company: null,
    role: 'Truck Driver',
  },
  {
    key: 'ehsan-ali',
    name: 'Ehsan Ali',
    company: 'Ali Fleet Services',
    role: 'Truck Owner',
  },
  {
    key: 'faisal-mehmood',
    name: 'Faisal Mehmood',
    company: null,
    role: 'Truck Driver',
  },
  {
    key: 'ghulam-abbas',
    name: 'Ghulam Abbas',
    company: 'Abbas Logistics',
    role: 'Truck Owner',
  },
  {
    key: 'hamid-sultan',
    name: 'Hamid Sultan',
    company: null,
    role: 'Truck Driver',
  },
  {
    key: 'imran-sheikh',
    name: 'Imran Sheikh',
    company: 'Sheikh Bus Service',
    role: 'Truck Owner',
  },
  {
    key: 'junaid-aslam',
    name: 'Junaid Aslam',
    company: null,
    role: 'Truck Driver',
  },
  {
    key: 'kamran-yousaf',
    name: 'Kamran Yousaf',
    company: 'Yousaf Auto Care',
    role: 'Mechanic',
  },
  {
    key: 'liaquat-baig',
    name: 'Liaquat Baig',
    company: null,
    role: 'Truck Driver',
  },
  {
    key: 'mudassar-khan',
    name: 'Mudassar Khan',
    company: 'Khan Freight',
    role: 'Truck Owner',
  },
  {
    key: 'nadeem-chaudhary',
    name: 'Nadeem Chaudhary',
    company: null,
    role: 'Truck Driver',
  },
  {
    key: 'omar-farooqi',
    name: 'Omar Farooqi',
    company: 'Farooqi Motors',
    role: 'Mechanic',
  },
  {
    key: 'qasim-latif',
    name: 'Qasim Latif',
    company: null,
    role: 'Truck Driver',
  },
  {
    key: 'rashid-mahmood',
    name: 'Rashid Mahmood',
    company: 'Mahmood Transport',
    role: 'Truck Owner',
  },
  {
    key: 'salman-tariq',
    name: 'Salman Tariq',
    company: null,
    role: 'Truck Driver',
  },
  {
    key: 'tariq-jameel',
    name: 'Tariq Jameel',
    company: 'Jameel Bus Co.',
    role: 'Truck Owner',
  },
  {
    key: 'usman-ghani',
    name: 'Usman Ghani',
    company: null,
    role: 'Truck Driver',
  },
];

// Segment order and exact totals/confirmed-counts from §19. Sums to
// 844 total / 619 confirmed.
const ROLE_SEGMENTS: {
  role: NamedMemberSeed['role'];
  total: number;
  confirmed: number;
}[] = [
  { role: 'Mechanic', total: 202, confirmed: 154 },
  { role: 'Truck Owner', total: 255, confirmed: 187 },
  { role: 'Truck Driver', total: 387, confirmed: 278 },
];

// Cross-joined to synthesize the bulk (non-named) Member names —
// 30x30 = 900 combinations, comfortably more than the 824 bulk rows
// needed (844 total minus the 20 named individuals above).
const FIRST_NAMES = [
  'Ahmed',
  'Ali',
  'Usman',
  'Bilal',
  'Hassan',
  'Hamza',
  'Zeeshan',
  'Tariq',
  'Imran',
  'Faisal',
  'Waqas',
  'Kamran',
  'Salman',
  'Adeel',
  'Naveed',
  'Shahid',
  'Rizwan',
  'Asif',
  'Junaid',
  'Farhan',
  'Aamir',
  'Sajid',
  'Nadeem',
  'Mudassar',
  'Qasim',
  'Rashid',
  'Omar',
  'Danish',
  'Liaquat',
  'Ghulam',
];
const LAST_NAMES = [
  'Raza',
  'Hussain',
  'Farooq',
  'Iqbal',
  'Ali',
  'Mehmood',
  'Abbas',
  'Sultan',
  'Sheikh',
  'Aslam',
  'Yousaf',
  'Baig',
  'Khan',
  'Chaudhary',
  'Farooqi',
  'Latif',
  'Malik',
  'Butt',
  'Chishti',
  'Qureshi',
  'Siddiqui',
  'Ansari',
  'Bhatti',
  'Cheema',
  'Dogar',
  'Gill',
  'Janjua',
  'Khokhar',
  'Mirza',
  'Rana',
];

interface MemberRow {
  key: string | null;
  name: string;
  company: string | null;
  role: NamedMemberSeed['role'];
  whatsappStatus: 'confirmed' | 'unconfirmed';
}

function buildMemberRows(): MemberRow[] {
  const rows: MemberRow[] = [];
  let bulkCounter = 0;

  for (const segment of ROLE_SEGMENTS) {
    const segmentRows: Omit<MemberRow, 'whatsappStatus'>[] =
      NAMED_MEMBER_SEEDS.filter((m) => m.role === segment.role).map((m) => ({
        key: m.key,
        name: m.name,
        company: m.company,
        role: m.role,
      }));

    while (segmentRows.length < segment.total) {
      const first = FIRST_NAMES[bulkCounter % FIRST_NAMES.length];
      const last =
        LAST_NAMES[
          Math.floor(bulkCounter / FIRST_NAMES.length) % LAST_NAMES.length
        ];
      segmentRows.push({
        key: null,
        name: `${first} ${last}`,
        company: null,
        role: segment.role,
      });
      bulkCounter += 1;
    }

    segmentRows.forEach((row, i) => {
      rows.push({
        ...row,
        whatsappStatus: i < segment.confirmed ? 'confirmed' : 'unconfirmed',
      });
    });
  }

  return rows;
}

// Populates the full §19 Member population on `contacts`: 844 rows
// (202 Mechanic / 255 Truck Owner / 387 Truck Driver), 619 with
// `whatsapp_status = 'confirmed'` (154/187/278 per segment — the
// reference table's numbers, hit exactly), spread evenly across the
// 20 seeded markets. Returns the full id list (for the
// engagement/interaction event generators, which just need a random
// Member to attribute an event to) and a name->id lookup for the 20
// named individuals `customer_requests`/`trials` reference directly.
async function seedDemoContacts(
  accountId: string,
  userId: string,
  regionIds: Map<string, string>,
  marketIds: Map<string, string>
): Promise<{ allContactIds: string[]; namedContactIds: Map<string, string> }> {
  const memberRows = buildMemberRows();
  const marketKeys = MARKETS_SEEDS.map((m) => m.key);
  const marketRegionKey = new Map(MARKETS_SEEDS.map((m) => [m.key, m.region]));

  const ids = memberRows.map(() => randomUUID());
  const namedContactIds = new Map<string, string>();

  const rows: Row[] = memberRows.map((m, i) => {
    const marketKey = marketKeys[i % marketKeys.length];
    const regionKey = marketRegionKey.get(marketKey)!;
    if (m.key) namedContactIds.set(m.key, ids[i]);

    return {
      id: ids[i],
      account_id: accountId,
      user_id: userId,
      phone: `+92300${String(i + 1).padStart(7, '0')}`,
      name: m.name,
      email: `${m.name.toLowerCase().replace(/\s+/g, '.')}.${i}@example.com`,
      company: m.company,
      role: m.role,
      region_id: regionIds.get(regionKey),
      market_id: marketIds.get(marketKey),
      opt_in_status: m.whatsappStatus === 'confirmed' ? 'opted_in' : 'pending',
      whatsapp_status: m.whatsappStatus,
      last_engagement:
        m.whatsappStatus === 'confirmed' ? hoursAgo(randomInt(1, 720)) : null,
      joined_date: daysFromNow(-randomInt(1, 365)),
    };
  });

  await insert('contacts', rows);
  return { allContactIds: ids, namedContactIds };
}

// ============================================================
// Seed sections — Phase 1 continued (Content, Requests, Trials, ...)
// ============================================================

interface ContentSeed {
  key: string;
  title: string;
  contentType: string;
  body: string;
  productCode: string | null;
  campaignKey: string | null;
  status:
    | 'Draft'
    | 'In Review'
    | 'Approved'
    | 'Scheduled'
    | 'Published'
    | 'Failed'
    | 'Archived';
}

const CONTENT_SEEDS: ContentSeed[] = [
  {
    key: 'poster-15w40',
    title: 'Rimula Heavy Duty 15W-40 — Trusted by Fleet Mechanics',
    contentType: 'poster',
    body: 'Reliable protection for heavy-duty diesel engines under demanding conditions. Ask your local BA for a trial.',
    productCode: 'RIM-HDD-15W40',
    campaignKey: 'fleet-checkup',
    status: 'Published',
  },
  {
    key: 'text-oil-change-signs',
    title: '5 Signs Your Truck Needs an Oil Change',
    contentType: 'text_post',
    body: 'Watch for these signs: dark exhaust smoke, unusual engine noise, reduced fuel economy, oil warning light, and longer-than-usual crank time.',
    productCode: null,
    campaignKey: 'fleet-checkup',
    status: 'Approved',
  },
  {
    key: 'image-coolant-reminder',
    title: 'Rimula Coolant Readiness Reminder',
    contentType: 'image',
    body: 'Winter is coming — book a coolant check with your local BA.',
    productCode: 'RIM-COOL-OAT',
    campaignKey: 'winter-coolant',
    status: 'In Review',
  },
  {
    key: 'campaign-post-pcm',
    title: 'Passenger Car Oil Change Promo',
    contentType: 'campaign_post',
    body: 'Keep your daily driver protected — ask about Rimula Passenger Car Motor Oil 5W-30.',
    productCode: 'RIM-PCM-5W30',
    campaignKey: 'passenger-car-push',
    status: 'Published',
  },
  {
    key: 'video-meet-ba',
    title: 'Meet Your Local Rimula BA',
    contentType: 'video',
    body: 'Draft script: introduce the local BA and how community members can reach them.',
    productCode: null,
    campaignKey: null,
    status: 'Draft',
  },
  {
    key: 'voice-check-oil',
    title: 'Voice Note: How to Check Engine Oil',
    contentType: 'voice_note',
    body: 'Script: a short walkthrough of checking engine oil level and condition with the dipstick.',
    productCode: null,
    campaignKey: null,
    status: 'Approved',
  },
];

async function seedContent(
  accountId: string,
  userId: string,
  productIds: Map<string, string>,
  campaignIds: Map<string, string>
): Promise<Map<string, string>> {
  const contentIds = new Map(CONTENT_SEEDS.map((c) => [c.key, randomUUID()]));
  const approvedStatuses = new Set(['Approved', 'Scheduled', 'Published']);

  await insert(
    'content',
    CONTENT_SEEDS.map((c) => ({
      id: contentIds.get(c.key),
      account_id: accountId,
      title: c.title,
      content_type: c.contentType,
      body: c.body,
      product_id: c.productCode ? productIds.get(c.productCode) : null,
      campaign_id: c.campaignKey ? campaignIds.get(c.campaignKey) : null,
      status: c.status,
      created_by: userId,
      approved_by: approvedStatuses.has(c.status) ? userId : null,
      approved_at: approvedStatuses.has(c.status) ? hoursAgo(48) : null,
    }))
  );
  return contentIds;
}

interface TranslationSeed {
  key: string;
  contentKey: string;
  language: 'ur' | 'ps' | 'pa' | 'ur-Roman';
  body: string;
}

const TRANSLATION_SEEDS: TranslationSeed[] = [
  {
    key: 'poster-15w40-ur',
    contentKey: 'poster-15w40',
    language: 'ur',
    body: 'ہیوی ڈیوٹی ڈیزل انجن آئل — فلیٹ مکینکس کا بھروسہ۔ اپنے مقامی بی اے سے ٹرائل کے لیے پوچھیں۔',
  },
  {
    key: 'poster-15w40-ps',
    contentKey: 'poster-15w40',
    language: 'ps',
    body: 'دروند دیوتي ډیزل انجن غوړ — د فلیټ ميخانيکانو باور. د آزمېښت لپاره خپل سیمه‌ییز BA ته اړیکه ونیسئ.',
  },
  {
    key: 'text-oil-change-signs-ur',
    contentKey: 'text-oil-change-signs',
    language: 'ur',
    body: 'ان علامات پر توجہ دیں: گہرا دھواں، غیر معمولی آواز، ایندھن کی کھپت میں اضافہ، آئل وارننگ لائٹ، اور اسٹارٹ ہونے میں تاخیر۔',
  },
  {
    key: 'campaign-post-pcm-pa',
    contentKey: 'campaign-post-pcm',
    language: 'pa',
    body: 'اپنی روزانہ گڈی نوں محفوظ رکھو — Rimula Passenger Car Motor Oil 5W-30 بارے پُچھو۔',
  },
];

async function seedContentTranslations(
  accountId: string,
  userId: string,
  contentIds: Map<string, string>
): Promise<Map<string, string>> {
  const translationIds = new Map(
    TRANSLATION_SEEDS.map((t) => [t.key, randomUUID()])
  );
  await insert(
    'content_translations',
    TRANSLATION_SEEDS.map((t) => ({
      id: translationIds.get(t.key),
      account_id: accountId,
      content_id: contentIds.get(t.contentKey),
      language: t.language,
      body: t.body,
      translated_by: userId,
    }))
  );
  return translationIds;
}

async function seedVoiceNotes(
  accountId: string,
  userId: string,
  contentIds: Map<string, string>,
  translationIds: Map<string, string>
): Promise<void> {
  const voiceNotes = [
    {
      contentKey: 'voice-check-oil',
      translationKey: null as string | null,
      language: 'ur' as const,
      filename: 'check-engine-oil-ur.ogg',
      durationSeconds: 48,
    },
    {
      contentKey: 'poster-15w40',
      translationKey: 'poster-15w40-ur',
      language: 'ur' as const,
      filename: 'rimula-15w40-ur.ogg',
      durationSeconds: 22,
    },
  ];

  await insert(
    'voice_notes',
    voiceNotes.map((v) => ({
      account_id: accountId,
      content_id: contentIds.get(v.contentKey),
      content_translation_id: v.translationKey
        ? translationIds.get(v.translationKey)
        : null,
      language: v.language,
      storage_path: `account-${accountId}/voice-notes/${v.filename}`,
      duration_seconds: v.durationSeconds,
      source: 'recorded',
      recorded_by: userId,
    }))
  );
}

interface CustomerRequestSeed {
  key: string;
  memberKey: string;
  productCode: string | null;
  campaignKey: string | null;
  type: string;
  source: string;
  status: 'NEW' | 'ASSIGNED' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED';
  assign: boolean;
  notes: string | null;
  /** Key into DEAL_SEEDS — this request was qualified into a Lead
   *  (§12: "once it's qualified it becomes ... a Lead"), backfilled
   *  onto customer_requests.deal_id after seedDeals runs. Not every
   *  request converts — most are left null, matching real usage. */
  dealKey?: string;
}

const CUSTOMER_REQUEST_SEEDS: CustomerRequestSeed[] = [
  {
    key: 'cr-1',
    memberKey: 'ahmed-raza',
    productCode: 'RIM-HDD-15W40',
    campaignKey: 'fleet-checkup',
    type: 'TRIAL_REQUEST',
    source: 'demo_whatsapp',
    status: 'ASSIGNED',
    assign: true,
    notes: 'Wants a trial for his own truck.',
    dealKey: 'deal-ahmed',
  },
  {
    key: 'cr-2',
    memberKey: 'bilal-hussain',
    productCode: 'RIM-PCM-5W30',
    campaignKey: 'passenger-car-push',
    type: 'PRODUCT_QUESTION',
    source: 'demo_whatsapp',
    status: 'RESOLVED',
    assign: true,
    notes: 'Asked about correct viscosity grade for his workshop customers.',
  },
  {
    key: 'cr-3',
    memberKey: 'chaudhry-farooq',
    productCode: 'RIM-HDD-15W40',
    campaignKey: 'fleet-checkup',
    type: 'PRODUCT_SUITABILITY',
    source: 'demo_whatsapp',
    status: 'NEW',
    assign: false,
    notes: 'Fleet of mixed heavy trucks — needs compatibility confirmation.',
  },
  {
    key: 'cr-4',
    memberKey: 'danish-iqbal',
    productCode: null,
    campaignKey: null,
    type: 'GENERAL_ENQUIRY',
    source: 'manual',
    status: 'CLOSED',
    assign: true,
    notes: 'Walked in to the demo booth at a community event.',
  },
  {
    key: 'cr-5',
    memberKey: 'ehsan-ali',
    productCode: 'RIM-COOL-OAT',
    campaignKey: 'winter-coolant',
    type: 'PRODUCT_INFORMATION',
    source: 'campaign',
    status: 'IN_PROGRESS',
    assign: true,
    notes: 'Wants coolant service pricing.',
    dealKey: 'deal-ehsan',
  },
  {
    key: 'cr-6',
    memberKey: 'faisal-mehmood',
    productCode: null,
    campaignKey: null,
    type: 'BA_CALL_REQUEST',
    source: 'demo_whatsapp',
    status: 'ASSIGNED',
    assign: true,
    notes: null,
  },
  {
    key: 'cr-7',
    memberKey: 'ghulam-abbas',
    productCode: 'RIM-HDD-15W40',
    campaignKey: null,
    type: 'PURCHASE_REQUEST',
    source: 'flow',
    status: 'NEW',
    assign: false,
    notes: 'Captured via Flows collect_input node.',
  },
  {
    key: 'cr-8',
    memberKey: 'hamid-sultan',
    productCode: null,
    campaignKey: null,
    type: 'FEEDBACK',
    source: 'whatsapp',
    status: 'RESOLVED',
    assign: true,
    notes: 'Positive feedback on BA responsiveness.',
  },
  {
    key: 'cr-9',
    memberKey: 'imran-sheikh',
    productCode: 'RIM-ATF-III',
    campaignKey: null,
    type: 'CONVERSION_REQUEST',
    source: 'demo_whatsapp',
    status: 'IN_PROGRESS',
    assign: true,
    notes: 'Ready to place a bulk order pending BA confirmation.',
    dealKey: 'deal-imran',
  },
  {
    key: 'cr-10',
    memberKey: 'junaid-aslam',
    productCode: 'RIM-PCM-5W30',
    campaignKey: 'passenger-car-push',
    type: 'PRODUCT_QUESTION',
    source: 'product_page',
    status: 'NEW',
    assign: false,
    notes: null,
  },
];

async function seedCustomerRequests(
  accountId: string,
  userId: string,
  namedContactIds: Map<string, string>,
  productIds: Map<string, string>,
  campaignIds: Map<string, string>
): Promise<Map<string, string>> {
  const requestIds = new Map(
    CUSTOMER_REQUEST_SEEDS.map((r) => [r.key, randomUUID()])
  );
  await insert(
    'customer_requests',
    CUSTOMER_REQUEST_SEEDS.map((r) => ({
      id: requestIds.get(r.key),
      account_id: accountId,
      contact_id: namedContactIds.get(r.memberKey),
      product_id: r.productCode ? productIds.get(r.productCode) : null,
      campaign_id: r.campaignKey ? campaignIds.get(r.campaignKey) : null,
      type: r.type,
      source: r.source,
      status: r.status,
      assigned_ba_id: r.assign ? userId : null,
      notes: r.notes,
    }))
  );
  return requestIds;
}

// ============================================================
// Deals (Lead, migration 055 — §9.0/§23 Phase 6)
// ============================================================
//
// `deals` is still a Kanban deal underneath (`pipeline_id`/`stage_id`
// NOT NULL, `contact_id` NOT NULL — migrations 001/002), so this
// seeds a "Sales Pipeline" + the same five spec-default stages the
// Pipelines page itself seeds on first open
// (`src/app/(dashboard)/pipelines/page.tsx`'s SPEC_DEFAULT_STAGES),
// rather than relying on the app to lazily create one — this script
// runs standalone, nothing lazily creates anything here.
//
// Added retroactively during Phase 8's §24 DoD review: this table was
// never seeded before, so Phase 7's funnel/campaign analytics showed
// 0 for Lead/BA Contact/Purchase on a fresh seed despite Trial-stage
// data being real. See docs/IMPLEMENTATION_PLAN.md's Phase 6 section
// for the correction.

const SPEC_DEFAULT_STAGES = [
  { name: 'New Lead', color: '#3b82f6', position: 0 },
  { name: 'Qualified', color: '#eab308', position: 1 },
  { name: 'Proposal Sent', color: '#f97316', position: 2 },
  { name: 'Negotiation', color: '#8b5cf6', position: 3 },
  { name: 'Won', color: '#22c55e', position: 4 },
];

interface DealSeed {
  key: string;
  memberKey: string;
  title: string;
  campaignKey: string | null;
  marketKey: string | null;
  status:
    | 'NEW'
    | 'ASSIGNED'
    | 'CONTACTED'
    | 'INTERESTED'
    | 'TRIAL_REQUESTED'
    | 'TRIAL_COMPLETED'
    | 'CONVERTED'
    | 'LOST';
  source: string;
  value: number;
  outcome: string | null;
  notes: string | null;
  assign: boolean;
}

// Every status in the funnel enum appears at least once so the
// Dashboard's funnel widget and the Leads board both render a real
// spread, not just NEW rows. Two land on `fleet-checkup` and two on
// `passenger-car-push` (both have real `cost` — §13's cost-per-lead
// metrics need at least one campaign with both cost and leads to
// show anything other than "no cost data").
const DEAL_SEEDS: DealSeed[] = [
  {
    key: 'deal-ahmed',
    memberKey: 'ahmed-raza',
    title: 'Ahmed Raza — fleet oil trial',
    campaignKey: 'fleet-checkup',
    marketKey: 'lahore',
    status: 'TRIAL_REQUESTED',
    source: 'customer_request',
    value: 0,
    outcome: null,
    notes: 'Trial scheduled for his own heavy-truck fleet.',
    assign: true,
  },
  {
    key: 'deal-bilal',
    memberKey: 'bilal-hussain',
    title: 'Bilal Hussain — workshop demo',
    campaignKey: 'passenger-car-push',
    marketKey: 'karachi',
    status: 'ASSIGNED',
    source: 'customer_request',
    value: 0,
    outcome: null,
    notes: 'Wants a demo trial for workshop customers.',
    assign: true,
  },
  {
    key: 'deal-bilal-2',
    memberKey: 'bilal-hussain',
    title: 'Bilal Hussain — reorder follow-up',
    campaignKey: null,
    marketKey: 'karachi',
    status: 'TRIAL_COMPLETED',
    source: 'manual',
    value: 12000,
    outcome: null,
    notes: 'Completed an earlier engine-oil trial; following up for a reorder.',
    assign: true,
  },
  {
    key: 'deal-chaudhry',
    memberKey: 'chaudhry-farooq',
    title: 'Chaudhry Farooq — fleet conversion',
    campaignKey: 'fleet-checkup',
    marketKey: 'multan',
    status: 'CONVERTED',
    source: 'campaign',
    value: 45000,
    outcome: 'Purchased a 20L drum after a successful fleet trial.',
    notes: null,
    assign: true,
  },
  {
    key: 'deal-danish',
    memberKey: 'danish-iqbal',
    title: 'Danish Iqbal — community event follow-up',
    campaignKey: null,
    marketKey: null,
    status: 'LOST',
    source: 'manual',
    value: 0,
    outcome: 'Went with a competitor after follow-up stalled.',
    notes: null,
    assign: true,
  },
  {
    key: 'deal-ehsan',
    memberKey: 'ehsan-ali',
    title: 'Ehsan Ali — coolant trial',
    campaignKey: 'winter-coolant',
    marketKey: 'faisalabad',
    status: 'TRIAL_REQUESTED',
    source: 'campaign',
    value: 0,
    outcome: null,
    notes: 'Coolant trial pending scheduling.',
    assign: true,
  },
  {
    key: 'deal-faisal',
    memberKey: 'faisal-mehmood',
    title: 'Faisal Mehmood — BA call',
    campaignKey: null,
    marketKey: null,
    status: 'CONTACTED',
    source: 'customer_request',
    value: 0,
    outcome: null,
    notes: 'BA returned the call; awaiting next steps.',
    assign: true,
  },
  {
    key: 'deal-ghulam',
    memberKey: 'ghulam-abbas',
    title: 'Ghulam Abbas — purchase interest',
    campaignKey: null,
    marketKey: null,
    status: 'INTERESTED',
    source: 'flow',
    value: 0,
    outcome: null,
    notes: 'Captured via a Flows collect_input node.',
    assign: false,
  },
  {
    key: 'deal-imran',
    memberKey: 'imran-sheikh',
    title: 'Imran Sheikh — ATF bulk order',
    campaignKey: null,
    marketKey: 'islamabad',
    status: 'LOST',
    source: 'customer_request',
    value: 0,
    outcome: 'Trial cancelled — chose a competitor product.',
    notes: null,
    assign: true,
  },
  {
    key: 'deal-junaid',
    memberKey: 'junaid-aslam',
    title: 'Junaid Aslam — passenger car oil',
    campaignKey: 'passenger-car-push',
    marketKey: null,
    status: 'NEW',
    source: 'product_page',
    value: 0,
    outcome: null,
    notes: null,
    assign: false,
  },
];

async function seedDeals(
  accountId: string,
  userId: string,
  namedContactIds: Map<string, string>,
  campaignIds: Map<string, string>,
  marketIds: Map<string, string>,
  regionIds: Map<string, string>,
  requestIds: Map<string, string>
): Promise<Map<string, string>> {
  const pipelineId = randomUUID();
  await insert('pipelines', [
    { id: pipelineId, user_id: userId, account_id: accountId, name: 'Sales Pipeline' },
  ]);
  const stageIds = SPEC_DEFAULT_STAGES.map(() => randomUUID());
  await insert(
    'pipeline_stages',
    SPEC_DEFAULT_STAGES.map((s, i) => ({
      id: stageIds[i],
      pipeline_id: pipelineId,
      name: s.name,
      color: s.color,
      position: s.position,
    }))
  );
  // New Leads land in the first stage regardless of Lead status —
  // `stage_id` (Kanban column) and `status` (Lead funnel state) are
  // two independent axes on this table, same distinction the Phase 6
  // Leads API draws (see src/lib/routing/create-lead.ts).
  const defaultStageId = stageIds[0];

  const marketKeyToRegionKey = new Map(
    MARKETS_SEEDS.map((m) => [m.key, m.region])
  );

  const dealIds = new Map(DEAL_SEEDS.map((d) => [d.key, randomUUID()]));
  await insert(
    'deals',
    DEAL_SEEDS.map((d) => {
      const regionKey = d.marketKey ? marketKeyToRegionKey.get(d.marketKey) : undefined;
      return {
        id: dealIds.get(d.key),
        user_id: userId,
        account_id: accountId,
        pipeline_id: pipelineId,
        stage_id: defaultStageId,
        contact_id: namedContactIds.get(d.memberKey),
        title: d.title,
        value: d.value,
        status: d.status,
        source: d.source,
        campaign_id: d.campaignKey ? campaignIds.get(d.campaignKey) : null,
        market_id: d.marketKey ? marketIds.get(d.marketKey) : null,
        region_id: regionKey ? regionIds.get(regionKey) : null,
        assigned_to: null, // deals.assigned_to -> profiles.id, not profiles.user_id (migration 002) — left unassigned in seed data rather than resolving the demo profile's row id here.
        outcome: d.outcome,
        notes: d.notes,
      };
    })
  );

  // Backfill customer_requests.deal_id for the requests that qualified
  // into one of these Leads (§12).
  for (const r of CUSTOMER_REQUEST_SEEDS) {
    if (!r.dealKey) continue;
    const { error } = await admin
      .from('customer_requests')
      .update({ deal_id: dealIds.get(r.dealKey) })
      .eq('id', requestIds.get(r.key));
    if (error) {
      throw new Error(
        `Failed to backfill customer_requests.deal_id for "${r.key}": ${error.message}`
      );
    }
  }

  return dealIds;
}

interface TrialSeed {
  memberKey: string | null;
  productCode: string;
  requestKey: string | null;
  /** Key into DEAL_SEEDS — §9.1: "a trial converts into (or
   *  originates from) a Lead." Not every trial has a matching Lead
   *  yet (e.g. a walk-in with no CRM record at all). */
  dealKey?: string;
  name: string;
  phone: string;
  role: string;
  market: string;
  vehicle: string;
  notes: string | null;
  status:
    | 'NEW'
    | 'REQUESTED'
    | 'ASSIGNED'
    | 'SCHEDULED'
    | 'COMPLETED'
    | 'CONVERTED'
    | 'CANCELLED';
  assign: boolean;
}

const TRIAL_SEEDS: TrialSeed[] = [
  {
    memberKey: 'ahmed-raza',
    productCode: 'RIM-HDD-15W40',
    requestKey: 'cr-1',
    dealKey: 'deal-ahmed',
    name: 'Ahmed Raza',
    phone: '+923000000001',
    role: 'Mechanic',
    market: 'Lahore',
    vehicle: 'Heavy Truck',
    notes: 'Trial for own fleet.',
    status: 'SCHEDULED',
    assign: true,
  },
  {
    memberKey: 'bilal-hussain',
    productCode: 'RIM-PCM-5W30',
    requestKey: null,
    name: 'Bilal Hussain',
    phone: '+923000000002',
    role: 'Mechanic',
    market: 'Karachi',
    vehicle: 'Passenger Car',
    notes: 'Requested for workshop customer demo.',
    status: 'REQUESTED',
    assign: false,
  },
  {
    memberKey: 'chaudhry-farooq',
    productCode: 'RIM-HDD-15W40',
    requestKey: null,
    dealKey: 'deal-chaudhry',
    name: 'Chaudhry Farooq',
    phone: '+923000000003',
    role: 'Truck Owner',
    market: 'Multan',
    vehicle: 'Heavy Truck',
    notes: null,
    status: 'CONVERTED',
    assign: true,
  },
  {
    memberKey: 'ehsan-ali',
    productCode: 'RIM-COOL-OAT',
    requestKey: 'cr-5',
    dealKey: 'deal-ehsan',
    name: 'Ehsan Ali',
    phone: '+923000000005',
    role: 'Truck Owner',
    market: 'Faisalabad',
    vehicle: 'Heavy Truck',
    notes: 'Coolant trial pending scheduling.',
    status: 'ASSIGNED',
    assign: true,
  },
  {
    memberKey: null,
    productCode: 'RIM-HDD-15W40',
    requestKey: null,
    name: 'Walk-in Prospect',
    phone: '+923000000099',
    role: 'Truck Driver',
    market: 'Lahore',
    vehicle: 'Heavy Truck',
    notes: 'No matching contact record yet — captured at a community event.',
    status: 'NEW',
    assign: false,
  },
  {
    memberKey: 'imran-sheikh',
    productCode: 'RIM-ATF-III',
    requestKey: null,
    dealKey: 'deal-imran',
    name: 'Imran Sheikh',
    phone: '+923000000009',
    role: 'Other',
    market: 'Islamabad',
    vehicle: 'Bus',
    notes: 'Cancelled — chose a competitor product.',
    status: 'CANCELLED',
    assign: true,
  },
];

async function seedTrials(
  accountId: string,
  userId: string,
  namedContactIds: Map<string, string>,
  productIds: Map<string, string>,
  requestIds: Map<string, string>,
  dealIds: Map<string, string>
): Promise<void> {
  await insert(
    'trials',
    TRIAL_SEEDS.map((t) => ({
      account_id: accountId,
      contact_id: t.memberKey ? namedContactIds.get(t.memberKey) : null,
      product_id: productIds.get(t.productCode),
      customer_request_id: t.requestKey ? requestIds.get(t.requestKey) : null,
      deal_id: t.dealKey ? dealIds.get(t.dealKey) : null,
      name: t.name,
      phone: t.phone,
      role: t.role,
      market: t.market,
      vehicle: t.vehicle,
      notes: t.notes,
      status: t.status,
      assigned_ba_id: t.assign ? userId : null,
    }))
  );
}

const ENGAGEMENT_EVENT_TYPES = [
  'DELIVERED',
  'READ',
  'REACTION',
  'REPLY',
  'CLICK',
  'LEAD',
  'TRIAL',
  'CONVERSION',
] as const;

async function seedEngagementEvents(
  accountId: string,
  campaignIds: Map<string, string>,
  contactIds: string[]
): Promise<void> {
  const campaigns = [...campaignIds.values()];
  const rows: Row[] = [];
  let hour = campaigns.length * ENGAGEMENT_EVENT_TYPES.length;

  for (const campaignId of campaigns) {
    for (const eventType of ENGAGEMENT_EVENT_TYPES) {
      rows.push({
        account_id: accountId,
        member_id: pick(contactIds),
        campaign_id: campaignId,
        event_type: eventType,
        event_value: eventType === 'CONVERSION' ? 45000 : null,
        source: 'demo_seed',
        occurred_at: hoursAgo(hour),
      });
      hour -= 1;
    }
  }

  await insert('engagement_events', rows);
}

const PRODUCT_INTERACTION_TYPES = [
  'viewed',
  'clicked',
  'enquiry',
  'interest',
  'trial_request',
  'lead',
] as const;

async function seedProductInteractions(
  accountId: string,
  productIds: Map<string, string>,
  campaignIds: Map<string, string>,
  contactIds: string[]
): Promise<void> {
  // A representative subset, not every product — this table is
  // attribution-trail data (§13), not a full product catalog dump.
  const featuredProducts = ['RIM-HDD-15W40', 'RIM-PCM-5W30', 'RIM-COOL-OAT'];
  const campaigns = [...campaignIds.values()];
  const rows: Row[] = [];
  let hour = featuredProducts.length * PRODUCT_INTERACTION_TYPES.length;

  for (const code of featuredProducts) {
    for (const interactionType of PRODUCT_INTERACTION_TYPES) {
      rows.push({
        account_id: accountId,
        contact_id: pick(contactIds),
        product_id: productIds.get(code),
        campaign_id: pick(campaigns),
        interaction_type: interactionType,
        created_at: hoursAgo(hour),
      });
      hour -= 1;
    }
  }

  await insert('product_interactions', rows);
}

async function seedWhatsAppSyncLog(
  accountId: string,
  productIds: Map<string, string>
): Promise<void> {
  const rows: Row[] = [];
  for (const [code, id] of productIds) {
    const seed = PRODUCT_SEEDS.find((p) => p.code === code)!;
    let syncStatus: string;
    let lastSyncedAt: string | null = null;
    let syncError: string | null = null;

    if (code === 'RIM-HDD-15W40') {
      syncStatus = 'Synced';
      lastSyncedAt = hoursAgo(48);
    } else if (code === 'RIM-HDD-20W50') {
      syncStatus = 'Sync Error';
      syncError = 'Catalogue rejected: missing required attribute (GTIN).';
    } else if (seed.status === 'published') {
      syncStatus = 'Pending Review';
    } else {
      syncStatus = 'Draft';
    }

    rows.push({
      account_id: accountId,
      product_id: id,
      sync_status: syncStatus,
      last_synced_at: lastSyncedAt,
      sync_error: syncError,
    });
  }
  await insert('whatsapp_sync_log', rows);
}

// ============================================================
// Orchestration
// ============================================================

async function main(): Promise<void> {
  console.log('Rimula demo seed — starting');

  const userId = await getOrCreateDemoUser();
  const accountId = await getAccountId(userId);
  console.log(`Seeding account ${accountId} (demo user ${userId})`);

  console.log('Cleaning up previous seed data...');
  await cleanup(accountId);

  console.log('Seeding community group...');
  await seedCommunityGroup(accountId, userId);

  console.log('Seeding product categories...');
  const categoryIds = await seedProductCategories(accountId);

  console.log('Seeding products...');
  const productIds = await seedProducts(accountId, userId, categoryIds);

  console.log('Seeding product images + applications...');
  await seedProductMedia(accountId, productIds);

  console.log('Seeding product claims...');
  await seedProductClaims(accountId, userId, productIds);

  console.log('Seeding vehicles...');
  const vehicleIds = await seedVehicles(accountId);

  console.log('Seeding verified product/vehicle compatibility...');
  await seedProductVehicles(accountId, userId, productIds, vehicleIds);

  console.log('Seeding campaigns...');
  const campaignIds = await seedCampaigns(accountId, userId, productIds);

  console.log('Seeding markets and regions...');
  const { regionIds, marketIds } = await seedMarketsRegions(accountId);

  console.log('Setting demo login BA fields...');
  await seedDemoUserBaFields(userId, regionIds, marketIds);

  console.log('Seeding demo Members (full §19 volumes: 844 contacts)...');
  const { allContactIds, namedContactIds } = await seedDemoContacts(
    accountId,
    userId,
    regionIds,
    marketIds
  );

  console.log('Seeding content...');
  const contentIds = await seedContent(
    accountId,
    userId,
    productIds,
    campaignIds
  );

  console.log('Seeding content translations...');
  const translationIds = await seedContentTranslations(
    accountId,
    userId,
    contentIds
  );

  console.log('Seeding voice notes...');
  await seedVoiceNotes(accountId, userId, contentIds, translationIds);

  console.log('Seeding customer requests...');
  const requestIds = await seedCustomerRequests(
    accountId,
    userId,
    namedContactIds,
    productIds,
    campaignIds
  );

  console.log('Seeding deals (Lead)...');
  const dealIds = await seedDeals(
    accountId,
    userId,
    namedContactIds,
    campaignIds,
    marketIds,
    regionIds,
    requestIds
  );

  console.log('Seeding trials...');
  await seedTrials(
    accountId,
    userId,
    namedContactIds,
    productIds,
    requestIds,
    dealIds
  );

  console.log('Seeding engagement events...');
  await seedEngagementEvents(accountId, campaignIds, allContactIds);

  console.log('Seeding product interactions...');
  await seedProductInteractions(
    accountId,
    productIds,
    campaignIds,
    allContactIds
  );

  console.log('Seeding WhatsApp sync log...');
  await seedWhatsAppSyncLog(accountId, productIds);

  console.log('');
  console.log(
    `Seeded ${allContactIds.length} Members (202 Mechanics / 255 Truck Owners / 387 Drivers, 619 WhatsApp-confirmed) across ${MARKETS_SEEDS.length} markets in ${REGIONS_SEEDS.length} regions.`
  );
  console.log('Done. Demo login:');
  console.log(`  email:    ${DEMO_EMAIL}`);
  console.log(`  password: ${DEMO_PASSWORD}`);
}

main().catch((err) => {
  console.error('Seed failed:', err instanceof Error ? err.message : err);
  process.exit(1);
});
