-- ============================================================
-- Make the message-template conflict target usable by PostgREST.
--
-- Migration 050 created this as a partial unique index:
--
--   UNIQUE (whatsapp_config_id, name, language)
--   WHERE whatsapp_config_id IS NOT NULL
--
-- PostgreSQL cannot infer that partial index for an unqualified
-- `ON CONFLICT (whatsapp_config_id, name, language)` statement, which is
-- the statement generated by Supabase/PostgREST. Template submission
-- therefore succeeded at Meta and then failed during the local upsert.
--
-- A regular unique index is safe here: PostgreSQL already treats NULLs as
-- distinct by default, so legacy rows whose whatsapp_config_id is NULL do
-- not conflict with one another.
-- ============================================================

DROP INDEX IF EXISTS public.message_templates_config_name_language_key;

CREATE UNIQUE INDEX message_templates_config_name_language_key
  ON public.message_templates (whatsapp_config_id, name, language);

